# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://developers.cloudflare.com/pages/platform/language-support-and-tools/

    steps:
    - uses: actions/checkout@v3

    - name: Cache node modules
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: ./.yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: make -C plugins ci-test
      env:
        CACHE_FOLDER: ${{ github.workspace }}/.yarn/cache

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: "**/*.junit.xml"
